name: "AdvancedJobs"
version: 1.9.7
main: net.advancedplugins.jobs.Core
website: https://advancedplugins.net/item/AdvancedJobs.187

libraries:
  - com.zaxxer:HikariCP:3.4.5
  - org.apache.commons:commons-math3:3.6.1

api-version: 1.13
softdepend:
  - PlaceholderAPI
  - Vault

commands:
  advancedjobs:
    description: "Main AdvancedJobs command"
    usage: /advancedjobs
    aliases:
      - ajob
      - aj
      - ajobs
      - jobs
      - job
  advancedjobsadmin:
    description: "AdvancedJobs Admin Command"
    usage: /advancedjobsadmin
    aliases:
      - ajadmin
      - ajobsadmin
      - aja

permissions:
  jobs.use:
    description: "Allows the player to use the /advancedjobs command"
    default: true